mutation createCli ($email: String!, $password: String!, $names: String!, $telephone: String!, $lastnames: String!, $location: String!){
  createClient(input: {email: $email, password: $password, names: $names, lastnames: $lastnames, location: $location, telephone: $telephone}){
    client{
      email
      password
      id

    }
  }
}

